name: Scrape Craigslist -> Supabase

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      # install deps from your repo's package.json
      - run: npm ci

      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          CITY: Calhoun
        run: node scripts/scrape_craigslist.mjs
